pipeline {
    agent any
    tools {
        dockerTool 'docker12'
    }
    environment {
        DOCKER_CREDS = credentials('3e63fecf-35f5-45c0-9139-8145bf6e8863')
        DOCKER_REPO = 'shalevnatan6/shalevnatandevops'
    }
    
    stages {

        stage('Checkout') {
            steps {
                 git branch: 'main', url: 'https://github.com/ShalevNatan/argocdTest.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKER_REPO:latest .
                '''
            }
        }
        stage('Push Docker Image') {
            steps {
                sh '''
                echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password "$(cat -)"
                docker push $DOCKER_REPO:latest
                '''
            }
        }
    }
}
